language: node_js
node_js:
#- '5'
- '5.1'
script:
- env
env:
  global:
    - secure: "f8p1pO7MbXQOTUXTywOhoNOdWXZUP5GKrMFSJ98CPUw/92fLwE4o0pNEEEQBcbVqJOXs0Rg1hrFPw/sP4RCF0EagTLFLAe4Khl9KVssegC8xwRWU56lSsm0leue+Q6di970qfpInEHvmVpxYIfKfkqzxYxGLqnRdZjt3HDyD9i0+6a7dMv+Le88yGY25MCzVIupc0OBEGkMraeDDxc8yIcnrz781dZN5vEqFEiWYJNJi80ULctmPqwGuRvaXUMckpASRThq9gxyrtYhAmDu8/x6rSlW62tKCsRchHwqnB1tkYfFnd5mrGaUA8EMwZ0POV1EdpMHofVyfRS0pS9dDnZgSQCbRvPDn3VTlTRbYAurM8097YIp4iwL/rCA65Der6VGAX3o8SwFcJSiHYi556bvLOR5MLEDYAdQylpUJhr5SDIr5juGP/lYFk/ocM2Ol7FHFi9mt7vFWs7DluADYUAZ8CcqnhEK6ZxoLfQXOAThSDvtViYJDtYgd7hmQvXibeIHCasuxvvWfYfXNywu8GQB0OW73HYtN3bkAv8Fr3GZn4XWQthlc7/tX6brzZ2Rvzer+aDS4lDfpFyWouuYXocLeFplTz369w0hW8zrPFPHguMNyoOGCgE6ISZTB89xL3l8ieV5LHz4CY6VLCNSOH7t/mN4vSbzmx8mX7HaKGPQ="
    - HOGE=FUGA
after_success:
- echo 'Success'
