language: node_js
node_js:
- 5.1
before_install:
- bash env.sh
deploy:
  provider: npm
  email: takou@zlab.co.jp
  api_key:
    secure: JTNRntzLmNahTNrG0WrP3WXcvQUFDBFrdp7buTwFH0kbUzxAwMTwM9EDhx8AG9d9PtrN5LLgIp6nW4T/jfGJ6EL4TH6SWnQRrFwpGXoTb7MEbbBrmv52y9Ze4bpkm/o7nwC0gJTBfChdUtBABYfNJWaZ5p6y1Al5vej5qi1mwhVmkfXUKOR+6g+lI/x61qxYUCbcV79t97AangonUaKwa8izjqad+YtcIjnJRgCUo0im99PI3nTt/WIKdy1z12iTKM2906UjiYzadD7TRbAiPKMHt2rylGNbMUcNBLuIpXzx4kWuMY082b2DJ4tv0ZLqnJ1hQw5oYEAPM3A+WsrUpubJYUWa4AlROPFHfd8PV76rshZ9mfVYRUpWcGnWnJ/oBrCmtBQ42ZS/5aSxYFyBxxatqRc2TPyec3JcGE1gXb3aRZ3Nas4OyQrdH9Fwgh9S++8Jcc226o/H4ZGlvSoxGRXYKoOFWA66z9k+MjHNtSYecxm+K5KlaRcNJA85MaLDwOm7y+u7vlMu0350WRVW6+Ev/1ZaEDbzOYKwGwRRmuHRwYsnP7zCWZ6Kx4j5pHOTdYHk/PmJWLSMMI0nr/8i8FWNffXiOG9LINEfsWKhWuqQRoUu+9MIFoTsJdGC5//eRBj4JvABx+hMoT5+FHrSggA6RBF/mfPToorWEg27dyI=
