language: node_js
node_js:
- '5.1'
before-install:
- bash env.sh
script:
- npm test
deploy:
  script: npm publish --registry $PUBLISH_REGISTRY
  provider: npm
  email: takou@zlab.co.jp
  api_key: $API_KEY

