language: node_js
node_js:
- 5.1
before_install:
- openssl aes-256-cbc -K $encrypted_3276039631c8_key -iv $encrypted_3276039631c8_iv
  -in .npmrc.enc -out .npmrc -d
- bash env.sh
deploy:
  script: npm publish
