language: node_js
node_js:
- '5.1'
before_install:
- sh env.sh
deploy:
  script: npm publish
env:
  global:
    secure: ea7Bql7231bd0TSQYgFNBMjDsfnyylvSTnz75viZbcuLvTcxCmLimym/uZ7ajI3a7pqwRBl+HYVuOZbHvA0e6EKo41zQmqqiV76vsihepCVuT4TZlWXsQFi0sPpIxjdurKjNmyWsyGvk5iDibGv2X2bg/BmO3BrWlRP+ewwV+Sno0cBII/XmbmlEmV/OaG7UbwKH625QgwqHdltSgJ2wv0C7L3sXPuhEmidHMlwx5e2vFxezZTfn4J7P6avvwMVfyFmfabnGr6opCIX8ZUaO3ZtXsCh9NDT/1faOXTPm7k0pUlK4/p9r+4AmpY7QbmHJIyqt3NY1gKD0TUxRks9IK7CA+Iyn1NzZXmFpEFKqWVapZvhZ0m7t98TTfxJmNdUPj/FwO++cpjb5LjZDwv86rEFqBKey03jVAKPRvU2VYGVX9qFxJ77HWSBYjpw8Q8VMBgZDTk9K6pddwchhOZNYwtx79pyMPevXyL9NfGhUbs3z3fNoWX3hmN1Cgeko8PmI2e3O8+ST99gAxQ03+n2XYiO9desBmEbzZpWHx+jMZy0OjwmukXP+dsp3JBcRJQQJdQFn/Bw6Fpb1s98ht4cg+Y3TZg7tssjFBY2zgqE6jwQa8oKHwrB1pRV1/Ck5egCEye0mFiS3LLpZ+zydy6a1yxAsczWqAQuQKWc6nMGpCT0=
