language: node_js
node_js:
- 5.1
before_install:
- bash env.sh
deploy:
  provider: npm
  email: takou@zlab.co.jp
  api_key:
    secure: "S33lCRiH4L+W8Zn68IjgGvj+FmB9KV3JQKBoptfQptF9OC5ZAKWYGEkuJaxBChytFtGhhEybQRt+mmmnC65o3NxPMah0boUSm5bg2eAyFaLW7SFdW4HXJv9yF8JPbwIwEUf/l+lIuPYeKRqpiBtVvud9h9Jnp9HJVCL4FGNRZaJNljefcTdzrf6LaGMFKZZyXA+q1r/sXcov0xAJA7aKse70D1LGOR4VYdqiJfl9C68h1ioO+mquhFsEuQH66u/2UkBQhzu3Cqg67Sry0N5VP/mDEuk1VwmSvgEW1laMo1Ga+uY8f/LfUaJuiV7J9v5bj3NOp9OOt7qDT+2c+le6q4oRML1Rv+eQIe7xgJMHth9uo4tbMxSo8sJtbC/o76xvzrphmOGHouDUhvX2IAMLLWZJ3tGudAYZIgm+8o5g/yky7BpawXbfaHxFiWOsHfzUD4dgsfSYKuWDya/rKKZrfp/rZOvP804QeCNQvNVA5jYjKS7u0R7jGLuh+yf07ApNniXUq7HtK2o+EAxvH6/PjQzClKa0ELc764QNMrEPaVzp5NceKacRH1aBtJW64xZIZo1qcl2VmDF+3OojKbx+r8my91wbfSbqnhhdWkmuQANznD+s7AJTR6fHOcfMTxw+kWn8OvhWp4KPAA9MiT8tXQMJHy04AYnk/X6Ua6XiHpo="
