language: node_js
node_js:
- '5.1'
#- '5'
before_install:
- sh env.sh
deploy:
  script: npm publish
env:
  global:
    secure: oiV2IQjXy3MIXl9P9/0c91hytizZiuQl3Jrs+dVkBoxUp1GqlbIs5Nk/31v6K5dPiemxoyELD8HIoqgKQwSe/X/Z9mVu+k3ov6SPTqHZhE/2Dp+xprBJ5hEC33+k3fPgFmdiUAjZc2WCg5F3J00amF19us/75N26+LEFkVZYgLTtr865h+pvHDIfdmrDZ46H+BfachE86Yr9UwvNhWhNf+cbUIn17WKH3n2jWjBDhziHIafv29ClYWQRrMcA9kPPRP8XEyStdspjLFVrO0tedb/IoPnMvxBHs/M66bN9/U6fIYAURNONI4bbWwWlscy+Ry6j8HZGSoQfiVARQ/yc7xufzLbtJoe2iJHq65yAUtsgTxXf4xXuO/17NDCD/uk74GmzYYjt6M0S3j9IdFmIEoVYbta9OPrBIImcMGOFuoz0yArMJrMZitvbFuKYJIf0IdN6xM0MAp26uY7mijEclJaWneQCLpJvXR+D4tQlqV85RvvZXGLRvs4ClUOVS2LE7Y6zT48qmSWn9z2NusdVYt1vXXjDfH0gWOEXHd6cuzlIgvzoQ4l6TvENx5/EqhAEN85TOHTtX/zvi9x+pu2zMCokax9UzbRHUyzi9zYEGqJeaoFOoe1X4etHGQsk6wNUixxyE+RVBbu7YXtfwEVK8Kj0WWPXMGaXzGpvwpP0Kzc=
