language: node_js
node_js:
- 5.1
before_install:
- bash env.sh
deploy:
  provider: npm
  email: takou@zlab.co.jp
  api_key:
    secure: E+WW7Fq8NPatD5liOw0BC0/dvL9i/V7JMR6jaLVmh1kJAIHdyZ2e4HjxnjoU0ic/pmOMDqBFACwm+DPW2Hc8siW1dT9gCeW39fH/9+F3cQlF7Bl+v7H6IU7DKkMSencraIA026hebpIi4mlZoRjAAQ9nFesZ+qSXsMwP+CN8Tzg0mz087UuVRBy5ovM6J1irOsC2bmmAqvVHdGKC94dxByRaEVvu6chS0tadQvF7qAH4Ge15mCwl6DldKdrm6QMT7g4AVtcK+4QYTe4gZtlujBYBU9MeNgZUgMHGasfCpg3+eAbckjztJ1Lr1+2sxvSYIc3u9xAe1QalxMsw/976uXO00vf84SK5q9M6eSEJsihU2G9C9VwbgykYclFmp8xB8Wrj4Irygu4Ebbw9Nf1HRbXpsth/4jDj24K8FqKXShGkrY6B3JrA6v2WlXQ5EVF4eRDEJvWxO3JX3WorZGOVIHwOX4zbGFK/u8VPOdunRp66zJsgQi2AQuRh1e85xNksBkQ8ax4scOZIEVPZeRBS6ew6c+eo1p11k+EW+qLcvIeKRXfjlavIVxsny/RiSpoh5+Poxn+W91C6oenXHxcfnoxCTr6KaXndAbPZAtCa/k54+IpHekyi7m96mKOVq1ZrJAGSJBFCNz0sBOd0OraAs+hixhLKSw0g3gSkgUrluUY=
after_success:
- echo 'Success'
dd:
  secure: kPXqLopSoJQR8ypbOYsYouroQuQtXaMsI5p7/+Y02v/5Kf17wJFoX+WP8djThtl6l6OATtuIIoMfSLlGu0XEYs98NUwTcoeTMApJW1hDSmVzV0Bb0DkqjUChpG/kjhYD9RxV3sHS4GdUdcaOpQB1FDqaztNFOVujw7P0XBCb7CB4AnS1fDyJSkRSWFaXkOCnLeQP4mMPsTDguAfCkmMyLBWeUn6cw7seF6cInaTa4ZVsDIJmbf0kmFYVbw2b7CaEqYcgLsbW30xZWC1qe936lbF/VB0OfvX6hQGmd1BqSvHidFgvOOwauQ05yqCYHYRuvIERd+DIXHbyeiwcBeCc8t3meWXcC+LdseOKqygWyRwlzaZkOrqu8NrIIFoqsv4qlZLt0G6ty8RnjcOh8Y5AfR7A9I/eaPsrlUlp2p/Hn9bYw+o9TJlcjNeZvgM1QSBwIXz9R33x5pSPd81Qk5+8I9bMwB8qHmlYHO/e3F9Y8KgBxeMswVB0J9BfOL0wxJJKS5vhF2tlk44aVGVnwIKMJHMcpbTEdrPlm68sN3V5eK6WFrXPBJFBLbChuoC1k07KngdZ4erBtfxvSHTTMEK0FJ7L5Mr9lYtIO2Y3iOwFiftRG/DLVbCklNoP6M86j2Gb5cPJPcIsUBnp4GUtysxenKu/b20IKx5c6nr5UR08hQk=
