language: node_js
node_js:
- '5.1'
before_install:
- sudo chmod a+x ./env.sh
- sudo chmod a+rw ./package.json ./.npmrc
- sudo ./env.sh
script:
- npm test
deploy:
  script: npm publish --registry $PUBLISH_REGISTRY
  provider: script
  email: takou@zlab.co.jp
  api_key: $API_KEY

