language: node_js
node_js:
- '5.1'
before_install:
- sudo chmod a+x ./env.sh
- sudo chmod a+rw ./.npmrc ./package.json
- ./env.sh
- env
script:
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: takou@zlab.co.jp
  api_key: $API_KEY
