language: node_js
node_js:
- '5'
- '5.1'
script:
- env
after_success:
- echo 'Success'
env:
  global:
    secure: BnEMjNrHdGnzPCI/JUfTDTilkFwWzx2BiiCqi6SgXO8dtyG+nGIaZNFpprE60BpKG0ePVpgjZRXz4Bs8FC/zYR0DM8s8xF9OaKebkiLoTZKnNQ+kjuCIX+OvZ3bIm5mj6e0AXvXTdaswojCHn9d7M21O0VrMzz9ygdJ8+Rix7CaYVJJI4uc0FCF3sq1lJ5fUubGkvo/UuYmTDabCJHX0WZEnUFQ6962fcDriJCpnzXybuA9gPkEPNHwDlM1EvqqBswOXT+d/COF4pSnIlzVUymYh4HZSndrrvrdF8aB0ekKv0sclOl8D7gL4y+RCtdU+tj+4bnEZZnHXmToJrkxH0EaF2K/SoLP5RLosDp4qcmB4FymQ6bsOzI5xIRpLg85CjSJieRYfj67t2KRGr1yfFoLdXg/uov4L5PxNitaWBXB5oSCYsIAe3GOIi1TLqaaW7I8uR89aYhUeOmuWXXsa5c9aDqD4qua0mWY/ZiL8uDnsbwTsq/6zxyWMSqiL0l5hgpkagdlNEG1c4mBOjnt9TrF+BlLp9OlTqAiN5pkp+7+eWlSUAI+kED1e0emNy52kV+4ZcsexnuZOPU1vCQD7KiJUuLqxjK+41LBqNCC5ovmXVWZgRG5k8Q2gjN3g/DADbSxP0l5iERVU7Epy0UIxHIq64hJV17N2lNTRM5t57QM=
