language: node_js
node_js:
- '5.1'
- '5'
before_install:
- bash env.sh
deploy:
  script: npm publish
env:
  global:
    secure: iRjMSo5NzDDQaINAG5qI1ux3QN+ggeCFRbsm0pxggK34QNkNaqe2fPKtVhXtfXZCkQU4YGaNpTcJ2V39MdsRMBkf32bo8i4XWlPHW5fIkGaZJFWZuq0KBVJulYhGZDsHz68Rdy4xVe28qoPiYugbvqQjA5z4KuX78vmwp1tCon04cbHk9YHAWamUtNxcVV2cjdLaMmb8oPaVYDEz39yJDIGlBgQ8FYROPpyQMX64CD7G8nyIO4KuQuVaqm7sx0ia9cUfqNw8cjzAR/haMd3UedaQCxbvOG2nwxFAHYbQy5ClSCKTF41FWAKXipTKPR9Wd8Qm+mDDHqT3a9HvA/WmDbh40fpMKqYrEcRyywWYSC3LiBzAjqGTIghcVQTVz7cUdAC/oYmmBGVgroKpWI7lbehlg3vY1F3NAD5jpFWUGtTWZ5gVF4CD67osl81iKZxgZEo7PZTeWQtvcbqYlVvafKsAI4YvttLYyiGJ3C2RMNWxRhEl/yK8dSlSQFZPqjbz96MbDZBur9v+zDmyKapNKxXUdeyqX14pVsZ7jmiRRTONXooNcureip/e+WL2AA9zNHXPg2BhzqafoWEf/GxD7G6mLME4xBHPfuQZbJ2qQr7ctTfM3R6xpDwvR81wzP7vEBAjsW2cQxqP+BukrrkOV9KtgShOivi3a73133GAGBg=
