language: node_js
node_js:
- '5.1'
before_deploy:
- bash env.sh
deploy:
  provider: npm
  email: $NPM_EMAiL
  api_key: $API_KEY
after_success:
- echo 'Success'
dd:
  secure: ZNEF6ySsNRiR1iHmFCMe7lE1546pOR/yK2KJqy7Ae9d/87LxQEm27jSDVbFVgMJPO/EOZY/oj2L7BCEd18+6VcK2ks/YMJHWpf+ioNU8gYKxDz+omDE6vm9drlQt3WATptdhV6dFmk87tYUph/FZse0obeIGYI8yBSd/XRIM7BxMKX4awhARqw9QDadWvZ3pEN3HDGFGmToXICMJyCfcrBSnkVxHVhqPEAXZ9D3no0sXy12wXzV0tO6dk5GopqxtLYLytO1EaYmMwUSRVhIp66u/qK6APzg8CYMLRW9IeC9azl4HUHaCmLVbDs9vjCpYs+9xAKqWbqhxpiGG3FanlqDLRrCQKD3zggKDRUOWWQBGJrWRq8hG0k3dGbwPp47Vg+Jw/mZS3L9aLVZmQxV9JF2mBJFiX2o/LM7SIE0hJnZPTWvWuHH3bqeJ/t10o7Ca62KM27p45sdHgH5dIEOE9iEJejndLzTK15g5DDkilIjYwipmx1dCvn3XvRbYDlzee2z3PPgevUWcnwlJY6xtkD+0IC7Ni3MJKnKyitDVLXFh11VrPFeMk+VPqnMZuOZ4+4IIZB/p+QU6TKHc1s7Kx469lcDwiGOd31aINXxEVe74sxkyaxeIpB0PxEZCCxW5gwokR9w7SwORk4mWypl4o9yrxyPUO35c/OGa2VtFQbw=
