language: node_js
node_js:
  - '5.1'
before_install:
  - bash env.sh
deploy:
  provider: npm
  email: $NPM_EMAiL
  api_key:
    secure: Od8OrxlHsQH7oy68E2K6dSqNADt8OWztYbnARavFGhwH46P0iE3efcoGCeGhYcaP9CaNTgWb5c1UnQwkr+itk5PXGks7NZkGOVmN+wXeIiJtcrkOk4BzGjoCadXHjih9E0lioDGaUg+db6wdXlUzutOSySpRI+jR7CM2UjdolN3+sX7Dek6jbzkwVTmBSEU2ca/eXApkni5x62XX4vok52F/0+NzojQV/vpPHCkFNDBeEB+GDtcmK1/qZKEYjoyAoKkDWAMRXQfDfNwEex9zrQ378NRbYFSSfACRWsI556MKpN6mJ6AOLlmFzPtmoKA4Jcf1q2aMxo3gXHPYszUFKNV/C/7FkkZ/xfe5szhDiga513rN3Lc9HR/oDGetCj4QyeILjdI95eIzhwg5QfJ3TE0xFzDjJYpNA63lLambk9iv2+OsXxHX8Nz09YX8Ae1ESxRI6IhyLhdHyspIXYFNnT3J+FbmcXIXc4SQzjEhbDblbmUur+MNqDgiRSsYAb3BbOsfRp3LvVfjL98Y8x+aWA2LWDBGFmwZNWNXveiXl5lfdrYJpKBcCj3WR4JKY1YSXl+LOtTT77+6y0iykhEC/tLQd5yp6rPrOYs7oOdSTuH7WLQRH83cc7DsGif4FaP+SjuY3RAn3j0YOYtxgoEkge1G242VNBtmCRrjvBsj6+k=
after_success:
  - echo 'Success'
