language: node_js
node_js:
- '5.1'
- '5'
env:
  global:
    secure: XoEMlNtg2UyS09/TJPC4ok6IA6m2tfVUEuoEwTdJH7Ar51wN0HZGug2d71VbNM2sESt86byHpsKvLIOft8d2b1Zx+O8QFPNmQjuEifuhjM7jMGqFxnPYISgDVH7BwHKMf6aE2D/PNwDQ3Vnkjdy/QkU6V/QB2J7Te3SEz5JJPyRqaHumfH6Dn88cgHjKHoLdNAw6OCpQiupDfTVEyqc7R1HVvgb9ndQV4up7Pbl7+Gc7mZzzuuLfg2kfp65ouVLevaz5wfa4tKdsmpxxp0o6L3Sru0zMOX9gzHTLZtYzwLTbs18NxaqVMMmptOyN7A8qAsFrVITqWxmE27F/qGs6LEGHh1tvkZYDiByKGAsxcXD5FyK8hpbJnftd39pthx9gyd7MQD6s1emfhDVlP1f73fHIvnWg4FVESv/AVLEpIjRvOc8aAXTUtk+gOccAxSh8oUcRKGDUtAIzrXBXJ7daxAwWDDCBjJFuX182m6ZMkjmFtMxnv1CdJxI3bgTq1fqEl/3P276P1v+iHXLJiwAaheNynTNgCSXWxXHS+0B1NE0O8feE79Cx6sbQb4IHsg7R+9YC3aaoNtzNn5ruTXfz1FewEn5dAsrwzM5bO0lsmlsb+vPby4lLN9fGN5h+srbKoP5pIg6/eAnfs8+fhAmiivk3tI+fPjfPpgR4pOcEIXg=
before_install:
- bash env.sh
deploy:
  script: npm publish
