language: node_js
node_js:
- '5.1'
before_install:
- sudo chmod a+x ./env.sh
- sudo chmod a+rw ./package.json
- ./env.sh
- npm config set registry=$REGISTRY
- npm config set _auth=$API_KEY
script:
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: takou@zlab.co.jp
  api_key:
    secure: "ETybhgf6A+yEqev0J1P0OIzd1gDhOlTM7XCpOGgvNHr3rXKYNTo6qSbeoG/m7g4PCjDi99Xs75h68RIdTHVdmlOVVos77BEYgc6yFpQZ5KzfDVOXO7VxRtECDBxaWmhOw/5wmVDIA8ZJmpB78W7jYThFwJ1ywviVbiULzXARFRY="
