language: node_js
node_js:
- '5.1'
before_install:
- sudo chmod a+x ./env.sh
- sudo chmod a+rw ./.npmrc
- ./env.sh
script:
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: takou@zlab.co.jp
  api_key:
    secure: EXtOiLxBA5tABYys4nJIC4xLXvdufQ423ZNwDisNXjvFOth/svWbnbvSJrcikc+zC8+5w/ZLhm+ZyVWjCZfsIzfy9uxiyMXavscT/aANw6njQV7xxENdxhc2Ah0+HpYHGSA4p9uE8Ypljv20TzG/wM7NqpwyZsN/fvcAeXJwOxY=
